export const PERMISSION_MODULE_REPOSITORY = Symbol(
  "PERMISSION_MODULE_REPOSITORY",
);
export const MODULE_QUERY_REPOSITORY = Symbol("MODULE_QUERY_REPOSITORY");
export const PERMISSION_MODULES_SERVICE = Symbol("PERMISSION_MODULES_SERVICE");
