export const MODULE_ROUTE_REPOSITORY = Symbol("MODULE_ROUTE_REPOSITORY");
export const ROUTE_QUERY_REPOSITORY = Symbol("ROUTE_QUERY_REPOSITORY");
export const MODULE_ROUTES_SERVICE = Symbol("MODULE_ROUTES_SERVICE");
